---
version: '3.7'
services:

  traefik:
    hostname: traefik
    image: traefik:v1.7
    container_name: traefik
    restart: always
    domainname: ${FQDN}
    networks:
      - default
      - traefik_proxy
    command: --api --docker
    ports:
      - "80:80"
      - "443:443"
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_DIR}/traefik:/etc/traefik
      - ${DOCKER_DIR}/shared:/shared

########################################################################################
# Downloaders
# https://hub.docker.com/r/haugene/transmission-openvpn/
########################################################################################

  transmission-vpn:
    container_name: transmission-vpn
    image: haugene/transmission-openvpn:latest-armhf
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
    # ports:
    # - "9091:9091"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DIR}/transmission-vpn:/data
      - ${DOCKER_DIR}/shared:/shared
      - ${EXTHDD_DIR}/Downloads/Torrents/watch:/data/watch
      - ${EXTHDD_DIR}/Downloads/Torrents/complete:/data/completed
      - ${EXTHDD_DIR}/Downloads/Torrents/incomplete:/data/incomplete
      - ${DOCKER_DIR}/transmission-vpn/openvpn:/etc/openvpn/torguard-custom
    environment:
      - OPENVPN_PROVIDER=${OPENVPN_PROVIDER}
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - OPENVPN_CONFIG=USA-SEATTLE
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=false
      - TRANSMISSION_UMASK=002
      - TRANSMISSION_RATIO_LIMIT=0.4999
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_WEB_UI=combustion
      - TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=1
      - TRANSMISSION_DOWNLOAD_LIMIT=5
    networks:
      - traefik_proxy

########################################################################################
# Indexers
# https://hub.docker.com/r/linuxserver/jackett
# https://hub.docker.com/r/linuxserver/radarr
# https://hub.docker.com/r/linuxserver/sonarr
########################################################################################

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/sonarr:/config
      - ${EXTHDD_DIR}/Media/TV:/tv
      - ${EXTHDD_DIR}/Downloads:/downloads
      - "/etc/localtime:/etc/localtime:ro"
    # ports:
    #   - 8989:8989
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sonarr"
      - "traefik.frontend.rule=Host:sonarr.${FQDN}"
      - "traefik.port=8989"
      - "traefik.docker.network=traefik_proxy"

  radarr:
    image: "linuxserver/radarr"
    container_name: "radarr"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/radarr:/config
      - ${EXTHDD_DIR}/Downloads:/downloads
      - ${EXTHDD_DIR}/Media/Movies:/movies
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=radarr"
      - "traefik.frontend.rule=Host:radarr.${FQDN}"
      - "traefik.port=7878"
      - "traefik.docker.network=traefik_proxy"

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_DIR}/jackett:/config
      - ${EXTHDD_DIR}/Jackett:/downloads
      - "/etc/localtime:/etc/localtime:ro"
    # ports:
    #   - 9117:9117
    restart: unless-stopped
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jackett"
      - "traefik.frontend.rule=Host:jackett.${FQDN}"
      - "traefik.port=9117"
      - "traefik.docker.network=traefik_proxy"

########################################################################################
# Media
# https://hub.docker.com/r/linuxserver/plex
# https://hub.docker.com/r/linuxserver/tautulli
########################################################################################

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - ${EXTHDD_DIR}/Plex/Config:/config
      - ${EXTHDD_DIR}/Media/TV:/data/tvshows
      - ${EXTHDD_DIR}/Media/Movies:/data/movies
      - ${EXTHDD_DIR}/Media/Other:/data/other
      - ${EXTHDD_DIR}/Plex/Transcode:/transcode
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plex"
      - "traefik.frontend.rule=Host:plex.${FQDN}"
      - "traefik.port=32400"
      - "traefik.docker.network=traefik_proxy"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
