loglevel = "ERROR"

[backends]
  [backends.backend-plex]
    [backends.backend-plex.servers]
      [backends.backend-plex.servers.server-plex-ext]
        url = "http://{{ .localIP }}:32400/web/index.html"
        weight = 0

[frontends]
  [frontends.frontend-plex]
    backend = "backend-plex"
    passHostHeader = true
    [frontends.frontend-plex.routes]
        [frontends.frontend-plex.routes.route-plex-ext]
            rule = "Host:plex.{{ . FQDN }}"
